apiVersion: v1
kind: Service
metadata:
  name: eks-2048-linux-service
  labels:
    app: eks-2048-linux-app
spec:
  selector:
    app: eks-2048-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80